src/assets/scss/components/checkbox/_variables.scss, src/assets/scss/themes/default.theme.scss, src/assets/scss/themes/example.theme.scss, src/assets/scss/utils/_functions.scss, src/assets/scss/utils/_mixins.scss, src/components/checkbox/index.vue, src/components/checkbox/script.ts, src/components/checkbox/style.scss, src/components/checkbox/template.html, src/components/index.js, src/index.ts, stories/documentation/checkbox.md, stories/index.stories.js, stories/pages/checkbox/default.stories.js, stories/templates/checkbox/default.template.js
New spacetab checkbox component
=> NEF-1565 | Checkbox component integration

src/components/checkbox/script.ts, src/components/checkbox/style.scss
- Fix hover effect on disabled item
=> - Fix disabled item can be clicked

src/assets/scss/components/button/_button-mixins.scss, src/assets/scss/utils/_functions.scss, src/components/button/style.scss
=> NEF-1621 | styles functions fix && button style fix

src/assets/scss/components/popover/_variables.scss, src/components/popover/script.ts, src/components/popover/template.html
=> NEF-1669 |  Popover mouseenter logic

package-lock.json, package.json
Reverts spacetabs/vue-components#28
=> Revert "0.2.1"

CHANGELOG.md, build/component-generator.js, build/generator-templates/story/documentation-file.template.txt, src/assets/scss/components/tabs/_variables.scss, src/assets/scss/themes/default.theme.scss, src/assets/scss/themes/example.theme.scss, src/assets/scss/themes/offers.theme.scss, src/components/index.js, src/components/tabs/index.vue, src/components/tabs/script.ts, src/components/tabs/style.scss, src/components/tabs/template.html, src/components/tabs/types.ts, src/index.ts, stories/assets/scss/index.scss, stories/assets/scss/tabs.scss, stories/documentation/tabs.md, stories/pages/tabs/default.stories.js, stories/templates/tabs/default.template.js
=> NEF-1678 | Added new component Tabs

.pre-commit.sh, CHANGELOG.md, build/generator-templates/story/documentation-file.template.txt, package-lock.json, package.json, src/assets/scss/components/collapser/_variables.scss, src/assets/scss/themes/default.theme.scss, src/assets/scss/themes/example.theme.scss, src/assets/scss/themes/offers.theme.scss, src/components/collapser/index.vue, src/components/collapser/script.ts, src/components/collapser/style.scss, src/components/collapser/template.html, src/components/index.js, src/components/popper/types.ts, src/components/tabs/script.ts, src/index.ts, stories/assets/scss/collapser.scss, stories/assets/scss/index.scss, stories/documentation/collapser.md, stories/pages/collapser/default.stories.js, stories/templates/collapser/default.template.js
=> TMC-84 | Added component Collapser

.storybook/webpack.config.js, src/assets/scss/components/tabs-collapsed/_variables.scss, src/assets/scss/components/tabs/_variables.scss, src/assets/scss/themes/default.theme.scss, src/assets/scss/themes/example.theme.scss, src/assets/scss/themes/offers.theme.scss, src/components/collapser/script.ts, src/components/collapser/style.scss, src/components/collapser/template.html, src/components/index.js, src/components/tabs-collapsed/index.vue, src/components/tabs-collapsed/script.ts, src/components/tabs-collapsed/style.scss, src/components/tabs-collapsed/template.html, src/components/tabs/_tab/index.vue, src/components/tabs/_tab/script.ts, src/components/tabs/_tab/template.html, src/components/tabs/script.ts, src/components/tabs/style.scss, src/components/tabs/template.html, src/components/tabs/types.ts, src/index.ts, stories/documentation/collapser.md, stories/documentation/tabs-collapsed.md, stories/documentation/tabs.md, stories/pages/tabs/collapsed.stories.js, stories/templates/tabs/collapsed.template.js, stories/templates/tabs/default.template.js
=> TMC-100 | Added component Tabs-collapsed

CHANGELOG.md, src/assets/scss/components/pagination/_variables.scss, src/components/pagination/script.ts, src/components/pagination/style.scss, src/components/pagination/template.html, src/components/pagination/types.ts, stories/assets/scss/index.scss, stories/assets/scss/pagination.scss, stories/documentation/pagination.md, stories/pages/pagination/default.stories.js, stories/templates/pagination/default.template.js
Calculation fix:
Big-number pages styles fix:
=> TMC-170 | Pagination fixes: props, group-pages calculating, long numbers styles

CHANGELOG.md, package-lock.json, package.json, src/components/popper/script.ts, stories/pages/popper/default.stories.js, stories/templates/popper/default.template.js
=> TMC-276 | Пофиксил ошибки в сторибуке поповера.

src/components/scrollbar/script.ts, stories/documentation/scrollbar.md, stories/pages/scrollbar/default.stories.js, stories/templates/scrollbar/default.template.js
- added functionality to customize minimal scroll size
- fixed bug with bad cursor floating on mouse move
- updated scrollbar documentation
- updated storybook pages
=> TMC-216: Minimal scroll size

src/components/popper/script.ts, src/components/popper/style.scss, src/components/popper/template.html, stories/documentation/popper.md
Also set append-to-body: true by default
=> TMC-297: Fix popper not appended to body bug.

src/assets/scss/utils/variables/_base.scss, src/components/popper/script.ts, src/components/popper/template.html
=> TMC_103 | Change default background color.

CHANGELOG.md, src/assets/scss/components/tabs/_variables.scss, src/assets/scss/themes/offers.theme.scss, src/assets/scss/themes/offers/_variables.scss, src/assets/scss/themes/offers/input.scss, src/assets/scss/themes/offers/tabs.scss, src/components/tabs/_list-collapsed/style.scss, src/components/tabs/_list-collapsed/template.html, src/components/tabs/_list-default/style.scss, src/components/tabs/_list-default/template.html, src/components/tabs/types.ts, stories/documentation/tabs.md, stories/pages/tabs/default.stories.js
- Добавил стилизацию табов для темы `offers`
- Добавил `disabled` свойство для табов
=> Add disabled prop to tabs components and styles to offer theme

CHANGELOG.md, src/assets/scss/components/popper/_variables.scss, src/components/popper/style.scss
=> TMC-423 | Added arrow's shadow to Popper

CHANGELOG.md, src/assets/scss/components/collapser/_variables.scss, src/assets/scss/themes/offers.theme.scss, src/assets/scss/themes/offers/_variables.scss, src/assets/scss/themes/offers/autocomplete.scss, src/components/autocomplete/template.html, src/components/collapser/script.ts, src/components/collapser/style.scss, src/components/collapser/template.html, src/components/table/script.ts, src/components/tabs/_list-collapsed/script.ts, src/components/tabs/_list-collapsed/template.html, src/components/tabs/script.ts, src/components/tabs/template.html, stories/documentation/autocomplete.md, stories/documentation/tabs.md
- Добавил стили для автокомплита для темя offers
- Добавил слоты suggestion-top иsuggestion-bottom
=> Add suggestion-top and suggestion-bottom slots to autocomplete component

CHANGELOG.md, package-lock.json, src/components/scrollbar/script.ts, src/components/scrollbar/style.scss
=> Revert "fix scrollbar auto height (#93)"

CHANGELOG.md, src/components/table/script.ts, src/components/table/template.html
Removed extra events to avoid unnecessary sorting, etc. when changing data during server sorting and paging.
=> Update table component

CHANGELOG.md, src/components/autocomplete/script.ts, src/components/autocomplete/template.html, src/components/input/style.scss, src/components/select/_select-content/script.ts, src/components/select/_select-content/template.html, src/components/select/_select-multiple/template.html, src/components/select/_select-single/template.html, stories/documentation/autocomplete.md, stories/pages/autocomplete/default.stories.js, stories/templates/autocomplete/default.template.js, stories/templates/select/default.template.js
**Features**
* Added `size` prop to `Autocomplete` and `Select`
**Maintenance**
* Fixed `Input`'s icon sizes with different value of `size` prop
=> TMC-558 | Fixes of Size prop

CHANGELOG.md, src/components/select/_select-dropdown/style.scss, src/components/select/_select-dropdown/template.html, stories/documentation/select.md
**Features**
* Added `no-options-message` slot to `Select`. If there're no options to display that slot will be visible
=> TMC-563 | Added no-options-message slot to Select

CHANGELOG.md, src/components/input/script.ts, src/components/select/_select-dropdown/style.scss, src/components/select/_select-dropdown/template.html, stories/documentation/select.md, stories/documentation/validator/component.md
**Features**
* Added `no-options-message` slot to `Select`. If there're no options to display that slot will be visible
**Maintenance**
* Fixed bug with not defined immediate watch value of validatable components.
=> Release 0.2.13

CHANGELOG.md, src/components/input/script.ts, src/components/select/_select-content/template.html, stories/documentation/input.md
**Features**
* Added `prevent-input` prop to `Input`.
**Maintenance**
* Fixed weird bug when typing in Select leaded to displaying clear icon
=> TMC-579 | Fixed typign in Select bug

CHANGELOG.md, src/components/autocomplete/script.ts, src/components/autocomplete/template.html, src/components/dialog/script.ts, src/components/input/script.ts, src/components/input/template.html, src/components/popper/script.ts, stories/pages/autocomplete/default.stories.js, stories/templates/autocomplete/default.template.js
Added focus and blur methods to Input and Autocomplete.
Added useReferenceWidth option to storybook of Autocomplete.
Fixed bug with useReferenceWidth do not work properly in Dropdown.
=> TMC-559 | Autocomplete fixes and inprovments

CHANGELOG.md, src/components/select/_select-multiple/script.ts, src/components/select/_select-multiple/style.scss, src/components/select/_select-multiple/template.html, src/components/select/_select-single/script.ts, src/components/select/_select-single/style.scss, src/components/select/_select-single/template.html, src/components/select/_select.base.ts, src/components/select/template.html, src/utils/validation.ts, stories/assets/scss/validate.scss, stories/documentation/validator/base.md, stories/documentation/validator/component.md, stories/pages/validator/component.stories.js, stories/templates/validator/component.template.js
**Features**
* Added `Validation` for `Select`
* Added `NotEmptyArrayRule` rule for `Validation`.
=> TMC-577 | Added validation to Select

CHANGELOG.md, src/assets/scss/components/button/_mixins.scss, src/assets/scss/themes/offers/button.scss, src/components/button/style.scss
* Component `Button`'s fixes: 
- Bug with icon coloring while `:active` and `:focus` states
- Bug with icon coloring with `secondary` and `text` `type` 
- Deleted additional white overlay while `loading` at the same time as `disabled`
=> OFR-346 | Button fixes: icon coloring and loading overlay fix

CHANGELOG.md, package-lock.json, package.json, src/assets/scss/components/button/_mixins.scss, src/assets/scss/themes/offers/button.scss, src/components/button/style.scss
* Component `Button`'s fixes: 
- Bug with icon coloring while `:active` and `:focus` states
- Bug with icon coloring with `secondary` and `text` `type` 
- Deleted additional white overlay while `loading` at the same time as `disabled`
=> Preparing 0.2.18 release

CHANGELOG.md, src/assets/scss/components/button/_mixins.scss, src/assets/scss/themes/offers/button.scss, src/components/button/style.scss
* Component `Button`'s fixes: 
- Bug with icon coloring while `:active` and `:focus` states
- Bug with icon coloring with `secondary` and `text` `type` 
- Deleted additional white overlay while `loading` at the same time as `disabled`
=> Prepare 0.2.18 release

CHANGELOG.md, src/assets/scss/components/button/_mixins.scss, src/assets/scss/themes/offers/button.scss, src/components/button/style.scss
* Component `Button`'s fixes: 
- Bug with icon coloring while `:active` and `:focus` states
- Bug with icon coloring with `secondary` and `text` `type` 
- Deleted additional white overlay while `loading` at the same time as `disabled`
=> Release 0.2.18
